root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/gateway"
bin = "./tmp/server"
include_ext = ["go", "json"]
exclude_dir = ["tmp", ".git"]
stop_on_error = true
delay = 100

[log]
time = true
color = true
